sonarqube-quality-gate 0.0.2
bitrise-io/bitrise-steplib pull request #2629
Opened 2020-08-20 09:30 UTC by abonham

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2020-08-20 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=2629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=2629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitrise-io/bitrise-steplib?pullRequest=2629) it.</sub>

2020-09-01 12:20 UTC, adborbas commented
Hi @abonham , could you please sign the CLA?

2020-09-08 05:58 UTC, abonham commented
Signed CLA!

2020-09-14 15:19 UTC, trapacska requested changes

2020-09-14 15:19 UTC, trapacska commented on steps/sonarqube-quality-gate/0.0.2/step.yml
> +  sonar_token: $SONAR_TOKEN
this input should be marked as sensitive: https://devcenter.bitrise.io/contributors/create-your-own-step/#sensitive-inputs

2020-09-14 15:19 UTC, trapacska commented on steps/sonarqube-quality-gate/0.0.2/step.yml
> +  organisation_key: null
maybe this is also sensitive

2020-10-06 19:24 UTC, sylank commented
@abonham This is a friendly ping message. I am just wondering if you mind fixing the review comments? 

:v:

2020-12-01 11:20 UTC, adborbas commented
Hi @abonham, I'll close this PR due to inactivity. Please feel free to reopen it incase you want to.

2020-12-01 11:20 UTC, closed without merging