oversecured 1.0.1
bitrise-io/bitrise-steplib pull request #3013
Opened 2021-05-02 17:47 UTC by bagipro

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [+] __I will not move an already shared step version's tag to another commit__
- [+] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [+] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [+] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [+] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2021-05-02 17:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3013) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3013) before we can accept your contribution.<br/><hr/>**bagipro** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitrise-io/bitrise-steplib?pullRequest=3013) it.</sub>

2021-05-05 16:34 UTC, tadam313 requested changes
thanks for the contribution, I have one tiny request, and please also sign the CLA for this contribution :) thanks 🙏

2021-05-05 16:34 UTC, tadam313 commented on steps/oversecured/1.0.1/step.yml
> +is_requires_admin_user: true
can you please remove this? It is deprecated now and has no effect :)

2021-05-06 11:30 UTC, Janos-vrancsik commented
> thanks for the contribution, I have one tiny request, and please also sign the CLA for this contribution :) thanks 🙏

@tadam313, @bagipro already signed the CLA for the initial Oversecured step contribution. AFAIK, he doesn't need to sign it again. :)

2021-05-06 12:02 UTC, tadam313 commented
> > thanks for the contribution, I have one tiny request, and please also sign the CLA for this contribution :) thanks 🙏
> 
> @tadam313, @bagipro already signed the CLA for the initial Oversecured step contribution. AFAIK, he doesn't need to sign it again. :)

sorry, we checked it and indeed it is signed, our CLA automation did not show it, we'll check the reasons why. This case, please disregard that part :)

2021-05-12 23:57 UTC, bagipro commented
Hey,
@tadam313 

sorry for the long response, updated this PR

@Janos-vrancsik 
yup, for some reason it always displays that I didn't accept it

2021-05-13 10:52 UTC, tadam313 approved these changes
LGTM

2021-05-13 10:52 UTC, merged