Pcloudy app upload 0.1.2
bitrise-io/bitrise-steplib pull request #3091
Opened 2021-06-25 07:17 UTC by shibupanda

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2021-06-25 13:04 UTC, godrei requested changes
Thanks for the contribution!
Please see my comments.

2021-06-27 16:30 UTC, shibupanda commented on steps/pcloudy-app-upload/0.1.2/step.yml
> +  - name: git
Shall I change it to curl instead of git?

2021-06-27 16:32 UTC, shibupanda commented on steps/pcloudy-app-upload/0.1.2/step.yml
> +  upload_path: $BITRISE_APK_PATH
You mean "$BITRISE_APK_PATH" needs to be remove

2021-06-29 07:10 UTC, godrei commented on steps/pcloudy-app-upload/0.1.2/step.yml
> -  upload_path: $BITRISE_APK_PATH
it seems the Step Input key was removed here, without the default value it should look like:

```
- upload_path:
  opts:
     description: |
       The app file you want to upload to Pcloudy, usually $BITRISE\_APK\_PATH or $BITRISE\_IPA\_PATH.
     is_expand: true
     is_required: true
     summary: Location of the IPA or APK that you want to upload.
     title: Location of APK or IPA
```

2021-06-29 07:11 UTC, godrei commented on steps/pcloudy-app-upload/0.1.2/step.yml
> +- opts:
it seems the Step Input key (`upload_path `) was removed here, without the default value it should look like:

```
- upload_path:
  opts:
     description: |
       The app file you want to upload to Pcloudy, usually $BITRISE\_APK\_PATH or $BITRISE\_IPA\_PATH.
     is_expand: true
     is_required: true
     summary: Location of the IPA or APK that you want to upload.
     title: Location of APK or IPA
```

2021-06-29 07:25 UTC, godrei commented on steps/pcloudy-app-upload/0.1.2/assets/icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 257"><defs><style>.cls-1{fill:#fff;}.cls-2{fill:#07223e;}</style></defs><title>Asset 1</title><g id="Layer_2" data-name="Layer 2"><g id="Layer
assets dir should go to the step group dir (`steps/pcloudy-app-upload/assets/`), not under a specific step version, example: https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/activate-ssh-key

2021-06-29 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitrise-io/bitrise-steplib?pullRequest=3091) it.</sub>

2021-07-01 10:37 UTC, shibupanda commented
@gergoovari Could you please review again. Thanks

2021-07-01 10:59 UTC, godrei commented
@shibupanda thanks for the changes, everything looks good to me!
I'm going to merge this PR, it seems in the [last commit](https://github.com/bitrise-io/bitrise-steplib/pull/3091/commits/d4e85a7899a49815c64a53fd61ea0f87fc49e761) the Step icon was removed, you can put it back in a new PR.

2021-07-01 10:59 UTC, godrei approved these changes

2021-07-01 10:59 UTC, merged