list-jira-tickets 0.0.1
bitrise-io/bitrise-steplib pull request #3146
Opened 2021-07-29 16:54 UTC by a-mlc

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2021-08-06 12:46 UTC, mateherber requested changes

2021-08-06 12:46 UTC, mateherber commented on steps/list-jira-tickets/0.0.1/step.yml
> +      JIRA ticket's Prefix
Maybe a sample in the description would help.

2021-08-06 12:48 UTC, mateherber commented
Hi @a-mlc!

Thank you very much for your contribution. I've added several remarks to the PR, please consider fixing them.

2021-08-10 14:23 UTC, lpusok commented on steps/list-jira-tickets/0.0.1/step.yml
> +- opts:
As long the YML is valid, we can and should accept it. I have seen a similar format in other contributions that did not yet cause issues.

2021-08-10 21:10 UTC, mateherber commented on steps/list-jira-tickets/0.0.1/step.yml
> +- opts:
Great, then I'll resolve this comment.

2021-08-17 19:07 UTC, closed without merging