appium-server 0.0.1
bitrise-io/bitrise-steplib pull request #3169
Opened 2021-08-15 22:35 UTC by moatazeldebsy

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2021-08-15 22:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3169) before we can accept your contribution.<br/><hr/>**Moataz Nabil** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitrise-io/bitrise-steplib?pullRequest=3169) it.</sub>

2021-08-16 10:53 UTC, koral-- commented on steps/appium-server/0.0.1/step.yml
> +  - name: wget
None of those are used in script but npm is OTOH.

2021-08-18 11:23 UTC, godrei requested changes
@moatazeldebsy thanks for the new Step, please review my comments.

This is how you can fix the issues: https://devcenter.bitrise.io/contributors/sharing-steps-with-all-bitrise-users/#fixing-issues-in-a-steplib-pull-request

2021-08-18 11:23 UTC, godrei commented on steps/appium-server/0.0.1/step.yml
> +title: Appium Server
`Run Appium Server` would be a better title: https://devcenter.bitrise.io/contributors/create-your-own-step/#the-title

2021-08-18 11:23 UTC, godrei commented on steps/appium-server/0.0.1/step.yml
> +- appium_version: Default Value - you can leave this empty if you want to
One of the value options should be the default value (`v1.21.0` or `v1.20.2`) for the input.

2021-08-18 20:46 UTC, closed without merging