emulator-wtf-android-test 1.1.0
bitrise-io/bitrise-steplib pull request #3327
Opened 2021-12-20 12:01 UTC by tauntz

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2021-12-20 12:01 UTC, tauntz commented
This is a follow-up to #3296

2022-01-04 08:32 UTC, godrei requested changes
Hi @tauntz ,

thanks for the changes!

I spotted 2 more issues:
- Missing summary for the `token` input
- In this version of the step the `ew-cli` is included in the step repository and executed by the step. The step refers to its path as: `./ew-cli`. This will not work as the current working directory points to `BITRISE_SOURCE_DIR` (by default the cloned project repository). To overcome this issue we use this: https://github.com/bitrise-steplib/steps-script/blob/master/step.sh#L3

2022-01-04 08:32 UTC, godrei commented on steps/emulator-wtf-android-test/1.1.0/step.yml
> +  token: null
Please add a summary to this input. (All inputs should have a title and summary at least, while the description is optional).

2022-01-04 08:34 UTC, godrei commented
Currently the step fails with an error: `chmod: ./ew-cli: No such file or directory`

2022-02-04 09:45 UTC, shams-ahmed commented
@tauntz Please let us know when the PR is ready for another review, will close for the time being.

2022-02-04 09:45 UTC, closed without merging