lambdatest-upload 1.0.1
bitrise-io/bitrise-steplib pull request #3457
Opened 2022-04-21 18:24 UTC by swngarg-lt

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2022-04-22 07:17 UTC, rohithmone commented
@tothszabi We have made few changes to the older version. Please review this PR. Thankyou

2022-04-22 08:11 UTC, mateherber requested changes

2022-04-22 08:11 UTC, mateherber commented on steps/lambdatest-upload/1.0.1/step.yml
> +    is_required: true
Adding a new `required` input with no default value is considered a "breaking change" so according to semver the version of the step will have to be `2.0.0`

2022-04-22 08:11 UTC, mateherber commented
Hey @rohithmone! 

Thanks for adding changes to your step, please read my review remark.

2022-04-22 10:47 UTC, rohithmone commented
Made the respective changes @mateherber

2022-04-25 08:28 UTC, mateherber approved these changes

2022-04-25 08:28 UTC, merged