dependency-check 1.0.0
bitrise-io/bitrise-steplib pull request #3674
Opened 2022-11-23 21:29 UTC by connor-alphero

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2022-11-23 21:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitrise-io/bitrise-steplib?pullRequest=3674) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitrise-io/bitrise-steplib?pullRequest=3674) it.</sub>

2022-12-06 09:57 UTC, ofalvai commented on steps/dependency-check/1.0.0/step.yml
> +title: Dependency Check
This title seems a bit too generic, how about `OWASP Dependency Check`?

2022-12-06 09:58 UTC, ofalvai commented on steps/dependency-check/1.0.0/step.yml
> +  brew:
Is it supposed to run on Linux VMs too? If so, you can define an `apt` dependency here (assuming the tool is available in APT)

https://devcenter.bitrise.io/en/builds/installing-tools-during-a-build.html#installing-tools-by-declaring-deps-in-the-bitrise-yml-file

2022-12-06 10:00 UTC, ofalvai commented on steps/dependency-check/1.0.0/step.yml
> +      Can be Markdown formatted text.
Some leftovers from the step template :)

2022-12-06 10:02 UTC, ofalvai requested changes
Great work @connor-alphero, thank you for developing this step. I left a few minor comments on the step.yml metadata.

2022-12-07 00:49 UTC, connor-alphero commented
@ofalvai Thank you for the feedback. 

I will incorporate what you pointed out and will open a fresh PR soon.

2022-12-07 00:49 UTC, closed without merging