steps-jira-post-build-details 0.0.1
bitrise-io/bitrise-steplib pull request #3772
Opened 2023-03-09 16:00 UTC by stanrud

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

2023-04-24 04:17 UTC, vshah23 commented
https://bitrise.io/integrations/steps/post-jira-comment-with-build-details

This step seems to provide similar functionality to the one you have created. Does it already satisfy your needs or are you able to contribute a feature enhancement to it instead?

2023-04-24 04:31 UTC, vshah23 requested changes
Step’s ID should not start with `steps-`.

2023-04-24 04:31 UTC, vshah23 commented on steps/steps-jira-post-build-details/0.0.1/step.yml
> +is_always_run: false
Since this is a `notification` type step `is_always_run` must be true.

2023-07-04 07:37 UTC, godrei commented
I'm closing this PR because of the inactivity.

2023-07-04 07:37 UTC, closed without merging